routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
//    Route::resource("/blogs", "BlogController")->except(["edit", "create"]);
    Route::resource("/document-type", "DocumentTypeController")->except(["edit", "create"]);
    Route::post("/articles/uploadFile", "ArticleController@uploadFile");
    Route::post("/articles/deleteFile", "ArticleController@deleteFile");
    Route::resource("/articles", "ArticleController");
    Route::resource("/documents", "DocumentController")->except("show");
    Route::resource("/settings", "SettingController")->except("show");
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes, WithScopeModel;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'active', 'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'active' => 'bool',
        'last_login' => 'datetime:d/m/Y H:i:s'
    ];

    /**
     * @param $value
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes["password"] = Hash::make($value);
    }

    /**
     * @param $value
     */
    public function setActiveAttribute($value)
    {
        if (is_string($value)) {
            $this->attributes["active"] = $value === "on" ? 1 : 0;
        }
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function article()
    {
        return $this->hasMany(Article::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function documents()
    {
        return $this->belongsTo(Document::class);
    }

    /**
     * @return bool
     */
    public function isAdmin()
    {
        return $this->hasRole('admin');
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeName(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("name", "LIKE", "%".$value."%");
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeEmail(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("email", $value);
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeActive(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("active", $value);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Resources\UserResource;
use App\Managers\UserManager;
use App\Repositories\UserRepository;
use App\User;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\View;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{

    private $roles;

    public function __construct()
    {
        $this->middleware("administrator-only");
    }

    /**
     * Display a listing of the resource.
     *
     * @param UserRepository $repository
     * @param UserManager $manager
     * @return LengthAwarePaginator|\Illuminate\Contracts\View\View|Builder|Builder[]|Collection|string
     */
    public function index(UserRepository $repository, UserManager $manager)
    {
        if (\request()->wantsJson()) {
            return $manager->datatable($repository->all());
        }

        return View::make("users.all", [
            "columns" => $manager->columns(),
            "dataTablesColumns" => $manager->dataTablesColumns(),
            "route" => route("users.index"),
            "config" => $manager->datatableConfig(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return View::make("users.index", [
            "title" => "save",
            "roles" => $this->allRoles(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserRequest $request
     * @param UserRepository $repository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, UserRepository $repository)
    {
        $create = new UserResource($user = $repository->create($request->only(["name", "email", "active", "password"])));
        $user->assignRole($request->input("roles"));
        return redirect()->back()->with([
            "message" => __("users.save.message"),
            "data" => $create->toArray($request)
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return UserResource
     */
    public function show(User $user)
    {
        return new UserResource($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(User $user)
    {
        return View::make("users.index", [
            "data" => (new UserResource($user))->toArray(\request()),
            "title" => "edit",
            "roles" => $this->allRoles(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserUpdateRequest $request
     * @param User $user
     * @param UserRepository $userRepository
     * @return UserResource|\Illuminate\Http\RedirectResponse
     */
    public function update(UserUpdateRequest $request, User $user, UserRepository $userRepository)
    {
        if ($request->has("roles") && !$user->hasRole($request->input("roles"))) {
            $user->assignRole($request->input("roles"));
        }

        $userRepository->update($user, $request->only(["name", "email", "active"]));
        if ($request->wantsJson()) {
            return new UserResource($user);
        }
        return redirect()->back()->with([
            "message" => __("users.edit.message"),
            "data" => (new UserResource($user))->toArray($request),
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @param UserRepository $userRepository
     * @return JsonResponse
     */
    public function destroy(User $user, UserRepository $userRepository)
    {
        foreach ($user->roles()->get() as $rol) {
            $user->removeRole($rol->name);
        }
        $userRepository->destroy($user);
        return JsonResponse::fromJsonString(__("users.controllers.destroy"));
    }

    /**
     * @return mixed
     */
    private function getRoles()
    {
        if (!is_a($this->roles, Role::class)) {
            $this->roles = resolve(Role::class);
        }
        return $this->roles;
    }

    /**
     * @return mixed
     */
    private function allRoles()
    {
        return $this->getRoles()->whereNotIn("name", ["admin"])->get();
    }
}

resources/views/users/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('users.all.title') }}
                        <a href="{{route("users.create")}}" class="btn btn-success btn-sm float-right"
                           data-toggle="tooltip" data-placement="right" title="{{__("users.all.tooltip-create")}}">
                            <i class="fa fa-plus"></i> Nuevo
                        </a>
                    </div>
                    <div class="card-body">
                        <x-alert type="success" vertical="top" horizontal="right"/>
                        <x-table :columns="$columns" :dataTablesColumns="$dataTablesColumns" :route="$route"
                                 :config="$config" name="users"/>
                        <x-modal :title="__('users.all.modal-title')" :close="true">
                            <div>
                                <div class="form-group row">
                                    <label for="staticName" class="col-sm-4 col-form-label"><b>Name</b></label>
                                    <div class="col-sm-8">
                                        <input type="text" readonly class="form-control-plaintext" id="staticName">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="staticEmail" class="col-sm-4 col-form-label"><b>Email</b></label>
                                    <div class="col-sm-8">
                                        <input type="text" readonly class="form-control-plaintext" id="staticEmail">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="staticRol" class="col-sm-4 col-form-label"><b>Last Login</b></label>
                                    <div class="col-sm-8">
                                        <input type="text" readonly class="form-control-plaintext" id="staticRol">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="staticActive" class="col-sm-4 col-form-label"><b>Active</b></label>
                                    <div class="col-sm-8">
                                        <input type="text" readonly class="form-control-plaintext" id="staticActive">
                                    </div>
                                </div>
                            </div>
                        </x-modal>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        var table;
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request active user **/
        async function active(userId) {
            let request = await functions.request(
                '{{url("users")}}/' + userId,
                'PATCH',
                {active: $("#active-" + userId).is(":checked") ? "on" : "off"}
            )
            if (request.data) {
                let message;
                if ($("#active-" + userId).is(":checked")) {
                    message = "{{__("users.all.enabled")}}";
                } else {
                    message = "{{__("users.all.disabled")}}";
                }

                $("#message").html(message);
                $("#alert").slideDown();
                setTimeout(function () {
                    $("#alert").fadeOut("slow");
                }, 3000)
            }
        }

        /** end request active user **/
        /** start request delete user **/
        function drop(userId) {
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                async function () {
                response = await functions.request('{{url("users")}}/' + userId, "DELETE");
                if (response) {
                    swal("{{__("general.delete.title")}}", response, "success");
                    table.ajax.reload();
                }
            });
        }

        /** end request delete user **/
        /** start request show user **/
        async function show(userId) {
            let request = await functions.request(
                '{{url("users")}}/' + userId,
                'GET'
            );

            if (request.data) {
                $("#staticName").val(request.data.name);
                $("#staticEmail").val(request.data.email);
                $("#staticActive").val(request.data.active);
                $("#staticRol").val(request.data.rol);

                $("#modal").modal({keyboard: false});
            }
        }

        /** end request show user **/
    </script>
@endsection

resources/views/users/button_action.blade.php
<div>
    <button type="button" class="btn btn-info btn-sm" onclick="show({{$model->getAttribute("id")}})"
            data-toggle="tooltip" data-placement="right" title="{{__("users.all.tooltip-show")}}">
        <i class="fa fa-eye"></i>
    </button>
    @if(!$model->isAdmin())
        <a href="{{route("users.edit", $model->getAttribute("id"))}}" class="btn btn-warning btn-sm"
           data-toggle="tooltip" data-placement="right" title="{{__("users.all.tooltip-edit")}}">
            <i class="fa fa-pencil"></i>
        </a>
        <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$model->getAttribute("id")}})"
                data-toggle="tooltip" data-placement="right" title="{{__("users.all.tooltip-destroy")}}">
            <i class="fa fa-trash"></i>
        </button>
    @endif
</div>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-6">
                <span id="message"></span>
                <div class="card">
                    <div class="card-header">{{ __(sprintf('users.%s.title', $title)) }}</div>
                    <div class="card-body">
                        @if ($errors->any() || session()->has("message"))
                            @php
                                $type = session()->has("message") ? "success" : "danger";
                                $message = session()->has("message") ? session()->get("message") : __('validation.message');
                            @endphp
                            <x-alert :message="$message" :type="$type" :show="true"/>
                        @endif
                        <form method="POST"
                              action="{{isset($data) ? route("users.update", $data["id"]) : route("users.store")}}">
                            @isset($data)
                                @method("PUT")
                            @endisset
                            @csrf
                            <div class="form-group">
                                <label for="name">{{__("users.labels.name")}}</label>
                                <input type="text"
                                       class="form-control"
                                       id="name"
                                       name="name"
                                       placeholder="{{__("users.labels.name")}}"
                                       value="{{ isset($data) ? $data["name"] : old("name") }}"
                                />
                            </div>
                            <div class="form-group">
                                <label for="email">{{__("users.labels.email")}}</label>
                                <input type="email"
                                       class="form-control"
                                       name="email"
                                       id="email"
                                       placeholder="{{__("users.labels.email")}}"
                                       value="{{ isset($data) ? $data["email"] : old("email") }}"
                                />
                            </div>

                            <div class="form-group">
                                <label for="roles">Roles</label>
                                <select class="form-control" name="roles" id="roles">
                                    <option @if(!(isset($data) && !$data["rol"])) selected @endif>-- Seleccione --
                                    </option>
                                    @foreach($roles as $rol)
                                        <option
                                            value="{{$rol->name}}"
                                            @if((isset($data) && $data["rol"] === $rol->getAttribute("name"))) selected @endif
                                        >
                                            {{\Illuminate\Support\Str::title($rol->getAttribute("name"))}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group custom-control custom-switch">
                                <input type="checkbox"
                                       class="custom-control-input"
                                       name="active"
                                       id="active"
                                       @if((isset($data) && $data["active"])) checked
                                       @elseif(old("active")) checked @endif
                                />
                                <label class="custom-control-label" for="active">{{__("users.labels.active")}}</label>
                            </div>

                            <button type="submit"
                                    class="btn btn-primary">{{__(sprintf('users.%s.button', $title))}}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")

@endsection

resources/views/users/switch.blade.php
@if(!$row->isAdmin())
    <div class="custom-control custom-switch" style="z-index: 0" data-placement="right"
         title="{{__("users.all.enable-disable")}}">
        <input type="checkbox"
               class="custom-control-input"
               id="active-{{$row->id}}"
               @if($row->active) checked @endif
               onchange="active({{$row->id}})"
        >
        <label class="custom-control-label" for="active-{{$row->id}}"></label>
    </div>
@endif