routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
//    Route::resource("/blogs", "BlogController")->except(["edit", "create"]);
    Route::resource("/document-type", "DocumentTypeController")->except(["edit", "create"]);
    Route::post("/articles/uploadFile", "ArticleController@uploadFile");
    Route::post("/articles/deleteFile", "ArticleController@deleteFile");
    Route::resource("/articles", "ArticleController");
    Route::resource("/documents", "DocumentController")->except("show");
    Route::resource("/settings", "SettingController")->except("show");
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Document
 * @package App
 */
class Document extends Model
{
    use WithScopeModel;

    /**
     * @var string[]
     */
    protected $fillable = [
        "title",
        "image_url",
        "document_url",
        "highlighted",
        "document_type_id",
        "lang",
        "user_id"
    ];

    /**
     * @var string[]
     */
    protected $casts = [
        "created_at" => "datetime:d/m/Y",
        "highlighted" => "boolean",
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function documentType()
    {
        return $this->belongsTo(DocumentType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeTitle(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("name", "LIKE", "%".$value."%");
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeDocumentType(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->whereHas("documentType", function ($query) use ($value) {
            return $query->whereId(intval($value));
        });
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeUser(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->whereHas("user", function ($query) use ($value) {
            return $query->whereId(intval($value));
        });
    }

    /**
     * @param $value
     */
    public function getHighlightedAttribute($value)
    {
        if (!empty($value)) {
            return $value ? __("general.boolean.yes") : __("general.boolean.no");
        }
    }
    /**
     * @param $value
     */
    public function setHighlightedAttribute($value)
    {
        if (is_string($value)) {
            $this->attributes["highlighted"] = $value === "on" ? 1 : 0;
        }
    }

    /**
     * @param $value
     * @return \Illuminate\Config\Repository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    public function getLangAttribute($value)
    {
        return config("general.language." . $value);
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeLang(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("lang", $value);
    }
}

app/DocumentType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class DocumentType extends Model
{
    use WithScopeModel;

    /**
     * @var string[]
     */
    protected $fillable = ["title", "image_url", "user_id"];

    /**
     * @var string[]
     */
    protected $casts = [
        "created_at" => "datetime:d/m/Y"
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function documents()
    {
        return $this->hasMany(Document::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeTitle(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("name", "LIKE", "%".$value."%");
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use App\DocumentType;
use App\Http\Requests\DocumentRequest;
use App\Http\Requests\DocumentUpdateRequest;
use App\Http\Resources\DocumentResource;
use App\Http\Resources\DocumentTypeResource;
use App\Managers\DocumentManager;
use App\Repositories\DocumentRepository;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;

class DocumentController extends Controller
{

    private $model;

    /**
     * Display a listing of the resource.
     *
     * @param DocumentRepository $repository
     * @param DocumentManager $manager
     * @return \Illuminate\Contracts\View\View
     */
    public function index(DocumentRepository $repository, DocumentManager $manager)
    {
        if (\request()->wantsJson()) {
            return $manager->datatable($repository->all());
        }
        
        return View::make("documents.all", [
            "columns" => $manager->columns(),
            "dataTablesColumns" => $manager->dataTablesColumns(),
            "route" => route("documents.index"),
            "config" => $manager->datatableConfig(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return View::make("documents.index", [
            "title" => "save",
            "language" => config('general.language'),
            "categories" => $this->allDocumentsType(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param DocumentRequest $request
     * @param DocumentRepository $repository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(DocumentRequest $request, DocumentRepository $repository)
    {
        $file = $request->file("file");
        $fileName = $file->getClientOriginalName();
        $file->storeAs("documents", $fileName, "public");
        $request->request->add([
            "user_id" => auth()->user()->getAuthIdentifier(),
            "document_url" => $fileName,
            "image_url" => $this->upload($request)
        ]);
        $this->renameFile($request);
        $create = new DocumentResource(
            $repository->create($request->only(
                "title",
                "user_id",
                "document_url",
                "document_type_id",
                "image_url",
                "lang",
                "highlighted"
            )
        ));
        return redirect()->back()->with([
            "message" => __("documents.save.message"),
            "data" => $create->toArray($request)
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Document $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Document $document
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Document $document)
    {
        Gate::authorize('update', $document);
        return View::make("documents.index", [
            "title" => "edit",
            "categories" => $this->allDocumentsType(),
            "language" => config('general.language'),
            "data" => (new DocumentResource($document))->toArray(\request()),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param DocumentUpdateRequest $request
     * @param \App\Document $document
     * @param DocumentRepository $repository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(DocumentUpdateRequest $request, Document $document, DocumentRepository $repository)
    {
        Gate::authorize('update', $document);
        $this->uploadDocument($request, $document);
        $request->request->add([
            "image_url" => $request->hasFile("image") ? $this->upload($request) : $request->input("image_url"),
            "user_id" => auth()->user()->getAuthIdentifier(),
        ]);
        $this->renameFile($request);
        $repository->update($document, $request->only([
            "title",
            "document_url",
            "document_type_id",
            "image_url",
            "lang",
            "highlighted",
            "image_url"
        ]));
        return redirect()->back()->with([
            "message" => __("documents.edit.message"),
            "data" => (new DocumentResource($document))->toArray($request)
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Document $document
     * @param DocumentRepository $repository
     * @return JsonResponse
     */
    public function destroy(Document $document, DocumentRepository $repository)
    {
        Gate::authorize('delete', $document);
        $repository->destroy($document);
        return JsonResponse::fromJsonString(__("documents.controllers.destroy"));
    }

    /**
     * @return mixed
     */
    private function getModel()
    {
        if (!is_a($this->model, DocumentType::class)) {
            $this->model = resolve(DocumentType::class);
        }

        return $this->model;
    }

    /**
     * @return mixed
     */
    private function allDocumentsType()
    {
        return $this->getModel()->select(["id", "title"])->get();
    }

    /**
     * @param Request $request
     * @param Document $document
     */
    private function uploadDocument(Request $request, Document $document)
    {
        if ($request->hasFile("file")) {
            $file = $request->file("file");
            $fileName = Str::uuid() . "." . $file->getClientOriginalExtension();
            if (Storage::disk("public")->exists("documents/" . $document->getAttribute("document_url"))) {
                Storage::disk("public")->delete("documents/" . $document->getAttribute("document_url"));
            }
            if (!Storage::disk("public")->exists("documents/" . $fileName)) {
                $file->storeAs("documents", $fileName, "public");
                $request->request->set("document_url", $fileName);
            }
        }
    }

    /**
     * @param Request $request
     * @return string|string[]
     */
    private function upload(Request $request)
    {
        $file = $request->file("image");
        $fileName = Str::uuid() . "." . $file->getClientOriginalExtension();
        $file->storeAs("articles", $fileName, "public");
        return $fileName;
    }

    /**
     * @param Request $request
     */
    private function renameFile(Request $request)
    {
        $path = "documents";
        if ($request->has("images") && !empty($request->input("images"))) {
            $images = [];
            foreach (json_decode($request->input("images"), true) as $image) {
                if (Storage::exists($path. "/". $image)) {
                    $extension = explode(".", $image);
                    $fileName = Str::uuid().".".end($extension);
                    Storage::move($path. "/". $image, $path. "/". $fileName);
                    $images[] = $fileName;
                }
            }
            $request->request->set("images", json_encode($images));
        }
    }
}

resources/views/documents/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('documents.all.title') }}
                        <a class="btn btn-success btn-sm float-right" href="{{route("documents.create")}}"
                           data-toggle="tooltip" data-placement="right" title="{{__("documents.save.title")}}">
                            <i class="fa fa-plus"></i> Nuevo
                        </a>
                    </div>
                    <div class="card-body">
                        <x-table :columns="$columns" :dataTablesColumns="$dataTablesColumns" :route="$route"
                                 :config="$config" name="documents"/>
                        <x-modal :title="__('documents.save.title')" :cancel="true" :save="true" size="modal-lg">
                            <form id="form">
                            <input type="hidden" id="edit">
                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">{{__("documents.labels.title")}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="title"
                                           placeholder="{{__("documents.labels.title")}}">
                                    <span class="error" id="error_title"></span>
                                </div>
                            </div>
                            </form>
                        </x-modal>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request delete title documents **/
        function drop(documentTypeId) {
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                function () {
                response = functions.request('{{url("documents")}}/' + documentTypeId, "DELETE")
                    .then(function (response) {
                        swal("{{__("general.delete.title")}}", response, "success");
                        table.ajax.reload();
                    }).catch(function (err) {
                        if (err.status === 403) {
                            alertError(err);
                        } else {
                            swal("Error", '{{__("general.error_server")}}', "error");
                            closeAlert();
                        }
                    });
            });
        }

        /** end request delete blog **/

        /** start request get title documents **/
        async function get(documentTypeId) {
            let response;
            clearErrors();
            response = await functions.request('{{url("/documents")}}/'+documentTypeId, "GET");
            if (response) {
                $("#titleModal").html("{{__("documents.edit.title")}}")
                $("#edit").val(documentTypeId);
                $("#title").val(response.data.title);
                $("#modal").modal("show");
            }
        }
        /** end request get blog **/

        function alertError(error) {
            swal("Error", error.responseJSON.message, "error");
            closeAlert();
        }

        function closeAlert() {
            setTimeout(function () {
                swal.close();
            }, 5000);
        }
    </script>
@endsection

resources/views/documents/button_action.blade.php
<div>
    <a class="btn btn-warning btn-sm" href="{{route("documents.edit", $model->getAttribute("id"))}}"
       data-toggle="tooltip" data-placement="right" title="{{__("document_type.all.tooltip-edit")}}">
        <i class="fa fa-pencil"></i>
    </a>
    <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$model->getAttribute("id")}})"
            data-toggle="tooltip" data-placement="right" title="{{__("document_type.all.tooltip-destroy")}}">
        <i class="fa fa-trash"></i>
    </button>
</div>

resources/views/documents/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <span id="message"></span>
                <div class="card">
                    <div class="card-header">{{ __(sprintf('documents.%s.title', $title)) }}</div>
                    <div class="card-body">
                        @if ($errors->any() || session()->has("message"))
                            @php
                                $type = session()->has("message") ? "success" : "danger";
                                $message = session()->has("message") ? session()->get("message") : __('validation.message');
                            @endphp
                            <x-alert :message="$message" :type="$type" :show="true"/>
                        @endif
                        <form method="POST" enctype="multipart/form-data"
                              action="{{isset($data) ? route("documents.update", $data["id"]) : route("documents.store")}}">
                            @isset($data)
                                @method("PUT")
                                <input type="hidden" name="document_url" value="{{$data["document_url"]}}">
                                <input type="hidden" name="image_url" value="{{$data["image_url"]}}">
                            @endisset
                            @csrf
                            <div class="form-group">
                                <label for="title">{{__("documents.labels.title")}}</label>
                                <input type="text"
                                       class="form-control"
                                       id="title"
                                       name="title"
                                       placeholder="{{__("documents.labels.title")}}"
                                       value="{{ isset($data) ? $data["title"] : old("title") }}"
                                />
                            </div>

                            <div class="form-group">
                                <label for="main_image">{{__("articles.labels.image")}}</label>
                                <div>
                                    <div class="file-loading">
                                        <input id="main_image" name="image" type="file">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="document_type">{{__("documents.labels.document_type")}}</label>
                                <select class="form-control" name="document_type_id" id="document_type_id">
                                    <option @if(!(isset($data) && !$data["document_type"])) selected @endif>--
                                        Seleccione --
                                    </option>
                                    @foreach($categories as $category)
                                        <option
                                            value="{{$category->getAttribute("id")}}"
                                            @if((isset($data) && $data["document_type"]->getAttribute("id") === $category->getAttribute("id"))) selected @endif
                                        >
                                            {{\Illuminate\Support\Str::title($category->getAttribute("title"))}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="custom-control custom-switch mt-4 mb-3" data-placement="right">
                                <input type="checkbox"
                                       class="custom-control-input"
                                       id="highlighted"
                                       name="highlighted"
                                       @if((isset($data) && $data["highlighted"] === "Si" || old("highlighted"))) checked @endif
                                >
                                <label class="custom-control-label" for="highlighted">
                                    {{__("articles.highlight")}}
                                </label>
                            </div>

                            <div class="form-group">
                                <label for="lang" class="col-form-label">{{__("articles.labels.lang")}}</label>
                                <select class="form-control" name="lang" id="lang" required>
                                    <option @if(!(isset($data) && !$data["lang"] || !empty(old("lang")))) selected @endif>--
                                        Seleccione --
                                    </option>

                                    @foreach($language as $key => $lang)
                                        <option
                                            value="{{$key}}"
                                            @if((isset($data) && $data["lang"] === $lang || old("lang") === $key)) selected @endif
                                        >
                                            {{\Illuminate\Support\Str::title($lang)}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="title">{{__("documents.labels.file")}}</label>
                                <div class="custom-file">
                                    <input
                                        type="file"
                                        class="custom-file-input"
                                        id="file"
                                        name="file"
                                        accept="application/pdf"
                                    >
                                    <label class="custom-file-label"
                                           for="file">{{__("documents.labels.input-file")}}</label>
                                </div>
                            </div>

                            <button type="submit"
                                    class="btn btn-primary">{{__(sprintf('documents.%s.button', $title))}}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        $(function () {
            @if(isset($data) && $data["document_url"])
            $(".custom-file-label").text("{{$data["document_url"]}}")
            @endif
            $("#file").change(function () {
                if ($(this).val() !== "") {
                    let fileName = $(this).val().split("\\");
                    $(".custom-file-label").text(fileName[fileName.length - 1]);
                }
            })
        })
        $(document).ready(function () {
            $("#main_image").fileinput({
                @if(isset($data) || old("image"))
                    initialPreview: "{{ \Illuminate\Support\Facades\Storage::disk("public")->url("articles/".$data["image_url"]) }}",
                    initialPreviewAsData: true,
                    deleteUrl: '{{url("articles/deleteFile")}}',
                    initialPreviewConfig:[
                        {
                            key: "{{ $data["image_url"] }}",
                        },
                    ],
                    ajaxDeleteSettings: {
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                    },
                @endif
                overwriteInitial: false,
                maxFileSize: 1500,
                showClose: false,
                showCaption: false,
                browseIcon: " <i class='fa fa-folder-open-o'></i>",
                browseLabel: '',
                removeLabel: '',
                removeIcon: '<i class="fa fa-trash"></i>',
                uploadUrl: '{{url("articles/uploadFile")}}',
                required: true,
                removeTitle: 'Cancel or reset changes',
                elErrorContainer: '#kv-avatar-errors-2',
                msgErrorClass: 'alert alert-block alert-danger',
                defaultPreviewContent: '<img src="{{asset("images/file-upload-image-icon.png")}}" class="image" alt="Subir imagen">',
                layoutTemplates: {main2: '{preview} {remove} {browse}'},
                allowedFileExtensions: ["jpg", "png", "gif", "jpeg",],
                ajaxSettings: {
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                previewZoomButtonIcons: {
                    prev: '<i class="fa fa-chevron-left"></i>',
                    next: '<i class="fa fa-chevron-right"></i>',
                    toggleheader: '<i class="fa fa-arrows-h"></i>',
                    fullscreen: '<i class="fa fa-arrows-alt"></i>',
                    borderless: '<i class="fa fa-arrows"></i>',
                    close: '<i class="fa fa-times"></i>'
                },
                fileActionSettings: {
                    showUpload: false,
                    showRemove: false,
                    zoomIcon: "<i class='fa fa-search'></i>",
                    zoomTitle: "Ver imagen",
                    removeIcon: "<i class='fa fa-trash'></i>",
                    removeTitle: "Quitar imagen"
                }
            });
        });
    </script>
@endsection