routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
//    Route::resource("/blogs", "BlogController")->except(["edit", "create"]);
    Route::resource("/document-type", "DocumentTypeController")->except(["edit", "create"]);
    Route::post("/articles/uploadFile", "ArticleController@uploadFile");
    Route::post("/articles/deleteFile", "ArticleController@deleteFile");
    Route::resource("/articles", "ArticleController");
    Route::resource("/documents", "DocumentController")->except("show");
    Route::resource("/settings", "SettingController")->except("show");
});

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use WithScopeModel;

    /**
     * @var string[]
     */
    protected $fillable = ["key", "value", "user_id"];

    /**
     * @var string[]
     */
    protected $casts = [
        "created_at" => "datetime:d/m/Y",
        "value" => "array",
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeUserId(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->whereHas("user", function ($query) use ($value) {
            return $query->whereId(intval($value));
        });
    }

    /**
     * @param Builder $query
     * @param $value
     * @return Builder
     */
    public function scopeKey(Builder $query, $value): Builder
    {
        return empty($value) ? $query : $query->where("key", "LIKE", "%".$value."%");
    }
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SettingRequest;
use App\Http\Resources\SettingResource;
use App\Managers\SettingManager;
use App\Repositories\SettingRepository;
use App\Setting;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param SettingRepository $repository
     * @param SettingManager $manager
     * @return \Illuminate\Contracts\View\View
     */
    public function index(SettingRepository $repository, SettingManager $manager)
    {
        if (\request()->wantsJson()) {
            return $manager->datatable($repository->all());
        }
        return View::make("settings.all", [
            "columns" => $manager->columns(),
            "dataTablesColumns" => $manager->dataTablesColumns(),
            "route" => route("settings.index"),
            "config" => $manager->datatableConfig(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return View::make("settings.index", [
            "title" => "save",
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SettingRequest $request
     * @param SettingRepository $repository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SettingRequest $request, SettingRepository $repository)
    {
        $request->request->add([
            "user_id" => auth()->user()->getAuthIdentifier(),
        ]);
        $create = new SettingResource(
            $repository->create($request->only("key",  "user_id", "value")));
        return redirect()->back()->with([
            "message" => __("settings.save.message"),
            "data" => $create->toArray($request)
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Setting $setting)
    {
        return View::make("settings.index", [
            "title" => "edit",
            "data" => (new SettingResource($setting))->toArray(\request()),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SettingRequest $request
     * @param \App\Setting $setting
     * @param SettingRepository $repository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SettingRequest $request, Setting $setting, SettingRepository $repository)
    {
        $repository->update($setting, $request->only(["key", "value"]));
        return redirect()->back()->with([
            "message" => __("settings.edit.message"),
            "data" => (new SettingResource($setting))->toArray($request)
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Setting $setting
     * @param SettingRepository $repository
     * @return JsonResponse
     */
    public function destroy(Setting $setting, SettingRepository $repository)
    {
        $repository->destroy($setting);
        return JsonResponse::fromJsonString(__("settings.controllers.destroy"));
    }
}

resources/views/settings/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('settings.all.title') }}
                        <a class="btn btn-success btn-sm float-right" href="{{route("settings.create")}}"
                           data-toggle="tooltip" data-placement="right" title="{{__("settings.save.title")}}">
                            <i class="fa fa-plus"></i> Nuevo
                        </a>
                    </div>
                    <div class="card-body">
                        <x-table :columns="$columns" :dataTablesColumns="$dataTablesColumns" :route="$route"
                                 :config="$config" name="settings"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        var table;
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request delete title blogs **/
        function drop(settingId) {
            console.log(settingId)
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                async function () {
                response = await functions.request('{{url("settings")}}/' + settingId, "DELETE");
                if (response) {
                    swal("{{__("general.delete.title")}}", response, "success");
                    table.ajax.reload();
                }
            });
        }

        /** end request delete blog **/
        /** start request show blog **/
        function show() {
            clearErrors();
            $("#titleModal").html("{{__("settings.save.title")}}")
            $("#edit").val("");
            $("#form").trigger("reset");
            $("#modal").modal({keyboard: false})
        }
        /** end request show blog **/

        /** start request create title blogs **/
        function create() {
            clearErrors();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{route("settings.store")}}', "POST", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#text-load").hide();
                $("#primary").removeAttr("disabled");
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Created!", "{{__("settings.save.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request create blog **/

        /** start request get title blogs **/
        async function get(blogId) {
            let response;
            clearErrors();
            response = await functions.request('{{url("/settings")}}/'+blogId, "GET");
            if (response) {
                $("#titleModal").html("{{__("settings.edit.title")}}")
                $("#edit").val(blogId);
                $("#title").val(response.data.title);
                $("#category").val(response.data.category_id).change();
                $("#modal").modal("show");
            }
        }
        /** end request get blog **/

        /** start request edit title blogs **/
        function edit() {
            clearErrors();
            let blogId = $("#edit").val();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{url("/settings")}}/'+blogId, "PATCH", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Updated!", "{{__("settings.edit.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request edit blog **/
        function execute() {
            if ($("#edit").val() === "") {
                return create();
            }
            return edit();
        }

        function clearErrors() {
            $("#error_title").html("").hide();
            $("#error_category").html("").hide();
        }
    </script>
@endsection

resources/views/settings/button_action.blade.php
<div>
    <a class="btn btn-warning btn-sm" href="{{route("settings.edit", $model->getAttribute("id"))}}"
       data-toggle="tooltip" data-placement="right" title="{{__("settings.all.tooltip-edit")}}">
        <i class="fa fa-pencil"></i>
    </a>
    <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$model->getAttribute("id")}})"
            data-toggle="tooltip" data-placement="right" title="{{__("settings.all.tooltip-destroy")}}">
        <i class="fa fa-trash"></i>
    </button>
</div>

resources/views/settings/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-10">
                <span id="message"></span>
                <div class="card">
                    <div class="card-header">{{ __(sprintf('settings.%s.title', $title)) }}</div>
                    <div class="card-body">
                        @if ($errors->any() || session()->has("message"))
                            @php
                                $type = session()->has("message") ? "success" : "danger";
                                $message = session()->has("message") ? session()->get("message") : __('validation.message');
                            @endphp
                            <x-alert :message="$message" :type="$type" :show="true"/>
                        @endif
                        <form method="POST"
                              action="{{isset($data) ? route("settings.update", $data["id"]) : route("settings.store")}}"
                              id="form"
                        >
                            @isset($data)
                                @method("PUT")
                            @endisset
                            @csrf
                            <div class="form-group">
                                <label for="title">{{__("settings.labels.key")}}</label>
                                <input type="text"
                                       class="form-control"
                                       id="key"
                                       name="key"
                                       placeholder="{{__("settings.labels.key")}}"
                                       value="{{ isset($data) ? $data["key"] : old("key") }}"
                                />
                            </div>
                            <input type="hidden" id="value" name="value">
                            <div id="output"></div>

                            <button type="submit"
                                    class="btn btn-primary" id="send">{{__(sprintf('settings.%s.button', $title))}}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        $(function () {
            let data = {!! isset($data) ? json_encode($data["value"]) : json_encode("{}") !!};
            let json = new JSONedtr(  data, '#output' );
            $("#file").change(function () {
                if ($(this).val() !== "") {
                    $(".custom-file-label").text($(this).val());
                }
            })
            $("#send").click(function (e) {
                console.log("click", e);
                if ($("#key").val() !== "" && Object.keys(json.getData()).length !== 0) {
                    $("#value").val(JSON.stringify(json.getData()))
                    //$("#form").submit();
                    console.log($("#form"));
                } else {
                    swal("Error", "{{__("general.validate.error")}}", "error");
                    e.preventDefault();
                    return false;
                }
            })
        })
    </script>
@endsection